let jazz_standards = [
    "All of Me",
    "All The Things You Are",
    "Alone Together",
    "Autumn Leaves",
    "Billie’s Bounce",
    "Black Orpheus (Manhã de Carnaval)",
    "Blue Bossa",
    "Body and Soul",
    "But Not For Me",
    "Bye Bye Blackbird",
    "Cherokee",
    "Confirmation",
    "Days of Wine and Roses",
    "Doxy",
    "Fly Me To The Moon",
    "Footprints",
    "Four",
    "Have You Met Miss Jones",
    "How High The Moon",
    "I Hear a Rhapsody",
    "I Love You",
    "I Remember You",
    "I’ll Remember April",
    "I’m Old Fashioned",
    "If I Should Lose You",
    "If I Were A Bell",
    "In A Mellow Tone",
    "In A Sentimental Mood",
    "It Could Happen To You",
    "Just Friends",
    "Misty",
    "My Funny Valentine",
    "Night and Day",
    "Oleo",
    "On Green Dolphin Street",
    "Recorda Me",
    "Satin Doll",
    "Stella By Starlight",
    "Scrapple From The Apple",
    "So What",
    "Solar",
    "St. Thomas",
    "Sweet Georgia Brown",
    "Take The A Train",
    "The Girl From Ipanema",
    "There Is No Greater Love",
    "There Will Never Be Another You",
    "Up Jumped Spring",
    "What Is This Thing Called Love",
    "Yesterdays",
]

var now = new Date();
var numStrings = 6
var fullDaysSinceEpoch = Math.floor(now/8.64e7);
document.getElementById("string_of_the_day").innerHTML = jazz_standards[fullDaysSinceEpoch % jazz_standards.length]

